i think this might be the way forward

diff --git a/base-install b/base-install
--- a/base-install
+++ b/base-install
@@ -1,6 +1,69 @@
 #!/bin/sh
+function checkEfi() {
+    ls /sys/firmware/efi/efivars 1>/dev/null 2>&1
+    echo $?
+}
 
-#loadkeys fi
-#timedatectl set-ntp true
+# Check internet connection
+function checkInternet() {
+    ping google.com -c 1 1>/dev/null 2>&1
 
-# Let's make this a lot simpler
+    if [[ $? -ne 0 ]]; then
+        echo "Couldn't connect to network. Maybe try again in a spiff?"
+        echo 1
+    fi
+
+    echo 0
+}
+
+function formatEfi() {
+sfdisk $jab_drive -X gpt<<EOF
+# 512M EFI boot partition
+,512M,U
+# 10G Swap partition
+,10G,S
+# Rest of the disk for root partition
+,,L
+EOF
+}
+
+function formatBios() {
+    # TODO: Gather enough motivation to actually do this
+    echo "BIOS implementation not completed yet"
+}
+
+function main() {
+    #loadkeys fi
+    #timedatectl set-ntp true
+    
+    conf_file=$(realpath $1)
+
+    if [[ -f $conf_file ]]; then source $conf_file; fi
+    
+    [[ -z $jab_drive ]] && export jab_drive="/dev/sda"
+    [[ -z $jab_swap ]] && export jab_swap=0
+    [[ -z $jab_swap_s ]] && export jab_swap_s=16G
+    [[ -z $jab_home_part ]] && export jab_home_part=1
+    [[ -z $jab_home_s ]] && export jab_home_s=0
+    [[ -z $jab_efi ]] && export jab_efi=$(checkEfi)
+    [[ -z $jab_online ]] && export jab_online=$(checkInternet)
+
+    echo "Checking for internet connection..."
+    if [[ ! jab_online ]]; then
+        echo "No internet connection. Aborting."
+        exit 1
+    fi
+
+    echo "Partitioning drive"
+    if [[ jab_efi ]]; then
+        formatEfi
+    else
+        formatBios
+        exit 2
+    fi
+
+    pacman -Sy reflector --noconfirm
+
+}
+
+main $@
